// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CouponWriteParam.proto

package com.akkw.protobuf.test.ptoto;

public final class CouponWriteParamProto {
  private CouponWriteParamProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CouponWriteParamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.akkw.protobuf.test.ptoto.CouponWriteParam)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
     */
    java.util.List<com.akkw.protobuf.test.ptoto.CouponProto.Coupon> 
        getCouponInfoListList();
    /**
     * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
     */
    com.akkw.protobuf.test.ptoto.CouponProto.Coupon getCouponInfoList(int index);
    /**
     * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
     */
    int getCouponInfoListCount();
    /**
     * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
     */
    java.util.List<? extends com.akkw.protobuf.test.ptoto.CouponProto.CouponOrBuilder> 
        getCouponInfoListOrBuilderList();
    /**
     * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
     */
    com.akkw.protobuf.test.ptoto.CouponProto.CouponOrBuilder getCouponInfoListOrBuilder(
        int index);

    /**
     * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
     */
    java.util.List<com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail> 
        getCouponDetailInfoListList();
    /**
     * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
     */
    com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail getCouponDetailInfoList(int index);
    /**
     * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
     */
    int getCouponDetailInfoListCount();
    /**
     * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
     */
    java.util.List<? extends com.akkw.protobuf.test.ptoto.CouponProto.CouponDetailOrBuilder> 
        getCouponDetailInfoListOrBuilderList();
    /**
     * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
     */
    com.akkw.protobuf.test.ptoto.CouponProto.CouponDetailOrBuilder getCouponDetailInfoListOrBuilder(
        int index);

    /**
     * <code>string invokeSource = 3;</code>
     * @return The invokeSource.
     */
    java.lang.String getInvokeSource();
    /**
     * <code>string invokeSource = 3;</code>
     * @return The bytes for invokeSource.
     */
    com.google.protobuf.ByteString
        getInvokeSourceBytes();

    /**
     * <code>map&lt;string, string&gt; extMap = 4;</code>
     */
    int getExtMapCount();
    /**
     * <code>map&lt;string, string&gt; extMap = 4;</code>
     */
    boolean containsExtMap(
        java.lang.String key);
    /**
     * Use {@link #getExtMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getExtMap();
    /**
     * <code>map&lt;string, string&gt; extMap = 4;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getExtMapMap();
    /**
     * <code>map&lt;string, string&gt; extMap = 4;</code>
     */

    java.lang.String getExtMapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; extMap = 4;</code>
     */

    java.lang.String getExtMapOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   *创建一个 User 对象
   * </pre>
   *
   * Protobuf type {@code com.akkw.protobuf.test.ptoto.CouponWriteParam}
   */
  public static final class CouponWriteParam extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.akkw.protobuf.test.ptoto.CouponWriteParam)
      CouponWriteParamOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CouponWriteParam.newBuilder() to construct.
    private CouponWriteParam(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CouponWriteParam() {
      couponInfoList_ = java.util.Collections.emptyList();
      couponDetailInfoList_ = java.util.Collections.emptyList();
      invokeSource_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CouponWriteParam();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akkw.protobuf.test.ptoto.CouponWriteParamProto.internal_static_com_akkw_protobuf_test_ptoto_CouponWriteParam_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetExtMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akkw.protobuf.test.ptoto.CouponWriteParamProto.internal_static_com_akkw_protobuf_test_ptoto_CouponWriteParam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam.class, com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam.Builder.class);
    }

    public static final int COUPONINFOLIST_FIELD_NUMBER = 1;
    private java.util.List<com.akkw.protobuf.test.ptoto.CouponProto.Coupon> couponInfoList_;
    /**
     * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.akkw.protobuf.test.ptoto.CouponProto.Coupon> getCouponInfoListList() {
      return couponInfoList_;
    }
    /**
     * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.akkw.protobuf.test.ptoto.CouponProto.CouponOrBuilder> 
        getCouponInfoListOrBuilderList() {
      return couponInfoList_;
    }
    /**
     * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
     */
    @java.lang.Override
    public int getCouponInfoListCount() {
      return couponInfoList_.size();
    }
    /**
     * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
     */
    @java.lang.Override
    public com.akkw.protobuf.test.ptoto.CouponProto.Coupon getCouponInfoList(int index) {
      return couponInfoList_.get(index);
    }
    /**
     * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
     */
    @java.lang.Override
    public com.akkw.protobuf.test.ptoto.CouponProto.CouponOrBuilder getCouponInfoListOrBuilder(
        int index) {
      return couponInfoList_.get(index);
    }

    public static final int COUPONDETAILINFOLIST_FIELD_NUMBER = 2;
    private java.util.List<com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail> couponDetailInfoList_;
    /**
     * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail> getCouponDetailInfoListList() {
      return couponDetailInfoList_;
    }
    /**
     * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.akkw.protobuf.test.ptoto.CouponProto.CouponDetailOrBuilder> 
        getCouponDetailInfoListOrBuilderList() {
      return couponDetailInfoList_;
    }
    /**
     * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
     */
    @java.lang.Override
    public int getCouponDetailInfoListCount() {
      return couponDetailInfoList_.size();
    }
    /**
     * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
     */
    @java.lang.Override
    public com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail getCouponDetailInfoList(int index) {
      return couponDetailInfoList_.get(index);
    }
    /**
     * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
     */
    @java.lang.Override
    public com.akkw.protobuf.test.ptoto.CouponProto.CouponDetailOrBuilder getCouponDetailInfoListOrBuilder(
        int index) {
      return couponDetailInfoList_.get(index);
    }

    public static final int INVOKESOURCE_FIELD_NUMBER = 3;
    private volatile java.lang.Object invokeSource_;
    /**
     * <code>string invokeSource = 3;</code>
     * @return The invokeSource.
     */
    @java.lang.Override
    public java.lang.String getInvokeSource() {
      java.lang.Object ref = invokeSource_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        invokeSource_ = s;
        return s;
      }
    }
    /**
     * <code>string invokeSource = 3;</code>
     * @return The bytes for invokeSource.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInvokeSourceBytes() {
      java.lang.Object ref = invokeSource_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        invokeSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTMAP_FIELD_NUMBER = 4;
    private static final class ExtMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.akkw.protobuf.test.ptoto.CouponWriteParamProto.internal_static_com_akkw_protobuf_test_ptoto_CouponWriteParam_ExtMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> extMap_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetExtMap() {
      if (extMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ExtMapDefaultEntryHolder.defaultEntry);
      }
      return extMap_;
    }

    public int getExtMapCount() {
      return internalGetExtMap().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; extMap = 4;</code>
     */

    @java.lang.Override
    public boolean containsExtMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetExtMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getExtMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getExtMap() {
      return getExtMapMap();
    }
    /**
     * <code>map&lt;string, string&gt; extMap = 4;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getExtMapMap() {
      return internalGetExtMap().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; extMap = 4;</code>
     */
    @java.lang.Override

    public java.lang.String getExtMapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExtMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; extMap = 4;</code>
     */
    @java.lang.Override

    public java.lang.String getExtMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExtMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < couponInfoList_.size(); i++) {
        output.writeMessage(1, couponInfoList_.get(i));
      }
      for (int i = 0; i < couponDetailInfoList_.size(); i++) {
        output.writeMessage(2, couponDetailInfoList_.get(i));
      }
      if (!getInvokeSourceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, invokeSource_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetExtMap(),
          ExtMapDefaultEntryHolder.defaultEntry,
          4);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < couponInfoList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, couponInfoList_.get(i));
      }
      for (int i = 0; i < couponDetailInfoList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, couponDetailInfoList_.get(i));
      }
      if (!getInvokeSourceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, invokeSource_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetExtMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        extMap__ = ExtMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, extMap__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam)) {
        return super.equals(obj);
      }
      com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam other = (com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam) obj;

      if (!getCouponInfoListList()
          .equals(other.getCouponInfoListList())) return false;
      if (!getCouponDetailInfoListList()
          .equals(other.getCouponDetailInfoListList())) return false;
      if (!getInvokeSource()
          .equals(other.getInvokeSource())) return false;
      if (!internalGetExtMap().equals(
          other.internalGetExtMap())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCouponInfoListCount() > 0) {
        hash = (37 * hash) + COUPONINFOLIST_FIELD_NUMBER;
        hash = (53 * hash) + getCouponInfoListList().hashCode();
      }
      if (getCouponDetailInfoListCount() > 0) {
        hash = (37 * hash) + COUPONDETAILINFOLIST_FIELD_NUMBER;
        hash = (53 * hash) + getCouponDetailInfoListList().hashCode();
      }
      hash = (37 * hash) + INVOKESOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getInvokeSource().hashCode();
      if (!internalGetExtMap().getMap().isEmpty()) {
        hash = (37 * hash) + EXTMAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetExtMap().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *创建一个 User 对象
     * </pre>
     *
     * Protobuf type {@code com.akkw.protobuf.test.ptoto.CouponWriteParam}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.akkw.protobuf.test.ptoto.CouponWriteParam)
        com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akkw.protobuf.test.ptoto.CouponWriteParamProto.internal_static_com_akkw_protobuf_test_ptoto_CouponWriteParam_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetExtMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableExtMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akkw.protobuf.test.ptoto.CouponWriteParamProto.internal_static_com_akkw_protobuf_test_ptoto_CouponWriteParam_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam.class, com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam.Builder.class);
      }

      // Construct using com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (couponInfoListBuilder_ == null) {
          couponInfoList_ = java.util.Collections.emptyList();
        } else {
          couponInfoList_ = null;
          couponInfoListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (couponDetailInfoListBuilder_ == null) {
          couponDetailInfoList_ = java.util.Collections.emptyList();
        } else {
          couponDetailInfoList_ = null;
          couponDetailInfoListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        invokeSource_ = "";

        internalGetMutableExtMap().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akkw.protobuf.test.ptoto.CouponWriteParamProto.internal_static_com_akkw_protobuf_test_ptoto_CouponWriteParam_descriptor;
      }

      @java.lang.Override
      public com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam getDefaultInstanceForType() {
        return com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam.getDefaultInstance();
      }

      @java.lang.Override
      public com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam build() {
        com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam buildPartial() {
        com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam result = new com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam(this);
        int from_bitField0_ = bitField0_;
        if (couponInfoListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            couponInfoList_ = java.util.Collections.unmodifiableList(couponInfoList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.couponInfoList_ = couponInfoList_;
        } else {
          result.couponInfoList_ = couponInfoListBuilder_.build();
        }
        if (couponDetailInfoListBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            couponDetailInfoList_ = java.util.Collections.unmodifiableList(couponDetailInfoList_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.couponDetailInfoList_ = couponDetailInfoList_;
        } else {
          result.couponDetailInfoList_ = couponDetailInfoListBuilder_.build();
        }
        result.invokeSource_ = invokeSource_;
        result.extMap_ = internalGetExtMap();
        result.extMap_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam) {
          return mergeFrom((com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam other) {
        if (other == com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam.getDefaultInstance()) return this;
        if (couponInfoListBuilder_ == null) {
          if (!other.couponInfoList_.isEmpty()) {
            if (couponInfoList_.isEmpty()) {
              couponInfoList_ = other.couponInfoList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCouponInfoListIsMutable();
              couponInfoList_.addAll(other.couponInfoList_);
            }
            onChanged();
          }
        } else {
          if (!other.couponInfoList_.isEmpty()) {
            if (couponInfoListBuilder_.isEmpty()) {
              couponInfoListBuilder_.dispose();
              couponInfoListBuilder_ = null;
              couponInfoList_ = other.couponInfoList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              couponInfoListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCouponInfoListFieldBuilder() : null;
            } else {
              couponInfoListBuilder_.addAllMessages(other.couponInfoList_);
            }
          }
        }
        if (couponDetailInfoListBuilder_ == null) {
          if (!other.couponDetailInfoList_.isEmpty()) {
            if (couponDetailInfoList_.isEmpty()) {
              couponDetailInfoList_ = other.couponDetailInfoList_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureCouponDetailInfoListIsMutable();
              couponDetailInfoList_.addAll(other.couponDetailInfoList_);
            }
            onChanged();
          }
        } else {
          if (!other.couponDetailInfoList_.isEmpty()) {
            if (couponDetailInfoListBuilder_.isEmpty()) {
              couponDetailInfoListBuilder_.dispose();
              couponDetailInfoListBuilder_ = null;
              couponDetailInfoList_ = other.couponDetailInfoList_;
              bitField0_ = (bitField0_ & ~0x00000002);
              couponDetailInfoListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCouponDetailInfoListFieldBuilder() : null;
            } else {
              couponDetailInfoListBuilder_.addAllMessages(other.couponDetailInfoList_);
            }
          }
        }
        if (!other.getInvokeSource().isEmpty()) {
          invokeSource_ = other.invokeSource_;
          onChanged();
        }
        internalGetMutableExtMap().mergeFrom(
            other.internalGetExtMap());
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.akkw.protobuf.test.ptoto.CouponProto.Coupon m =
                    input.readMessage(
                        com.akkw.protobuf.test.ptoto.CouponProto.Coupon.parser(),
                        extensionRegistry);
                if (couponInfoListBuilder_ == null) {
                  ensureCouponInfoListIsMutable();
                  couponInfoList_.add(m);
                } else {
                  couponInfoListBuilder_.addMessage(m);
                }
                break;
              } // case 10
              case 18: {
                com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail m =
                    input.readMessage(
                        com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail.parser(),
                        extensionRegistry);
                if (couponDetailInfoListBuilder_ == null) {
                  ensureCouponDetailInfoListIsMutable();
                  couponDetailInfoList_.add(m);
                } else {
                  couponDetailInfoListBuilder_.addMessage(m);
                }
                break;
              } // case 18
              case 26: {
                invokeSource_ = input.readStringRequireUtf8();

                break;
              } // case 26
              case 34: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                extMap__ = input.readMessage(
                    ExtMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableExtMap().getMutableMap().put(
                    extMap__.getKey(), extMap__.getValue());
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.akkw.protobuf.test.ptoto.CouponProto.Coupon> couponInfoList_ =
        java.util.Collections.emptyList();
      private void ensureCouponInfoListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          couponInfoList_ = new java.util.ArrayList<com.akkw.protobuf.test.ptoto.CouponProto.Coupon>(couponInfoList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.akkw.protobuf.test.ptoto.CouponProto.Coupon, com.akkw.protobuf.test.ptoto.CouponProto.Coupon.Builder, com.akkw.protobuf.test.ptoto.CouponProto.CouponOrBuilder> couponInfoListBuilder_;

      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
       */
      public java.util.List<com.akkw.protobuf.test.ptoto.CouponProto.Coupon> getCouponInfoListList() {
        if (couponInfoListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(couponInfoList_);
        } else {
          return couponInfoListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
       */
      public int getCouponInfoListCount() {
        if (couponInfoListBuilder_ == null) {
          return couponInfoList_.size();
        } else {
          return couponInfoListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
       */
      public com.akkw.protobuf.test.ptoto.CouponProto.Coupon getCouponInfoList(int index) {
        if (couponInfoListBuilder_ == null) {
          return couponInfoList_.get(index);
        } else {
          return couponInfoListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
       */
      public Builder setCouponInfoList(
          int index, com.akkw.protobuf.test.ptoto.CouponProto.Coupon value) {
        if (couponInfoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCouponInfoListIsMutable();
          couponInfoList_.set(index, value);
          onChanged();
        } else {
          couponInfoListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
       */
      public Builder setCouponInfoList(
          int index, com.akkw.protobuf.test.ptoto.CouponProto.Coupon.Builder builderForValue) {
        if (couponInfoListBuilder_ == null) {
          ensureCouponInfoListIsMutable();
          couponInfoList_.set(index, builderForValue.build());
          onChanged();
        } else {
          couponInfoListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
       */
      public Builder addCouponInfoList(com.akkw.protobuf.test.ptoto.CouponProto.Coupon value) {
        if (couponInfoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCouponInfoListIsMutable();
          couponInfoList_.add(value);
          onChanged();
        } else {
          couponInfoListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
       */
      public Builder addCouponInfoList(
          int index, com.akkw.protobuf.test.ptoto.CouponProto.Coupon value) {
        if (couponInfoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCouponInfoListIsMutable();
          couponInfoList_.add(index, value);
          onChanged();
        } else {
          couponInfoListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
       */
      public Builder addCouponInfoList(
          com.akkw.protobuf.test.ptoto.CouponProto.Coupon.Builder builderForValue) {
        if (couponInfoListBuilder_ == null) {
          ensureCouponInfoListIsMutable();
          couponInfoList_.add(builderForValue.build());
          onChanged();
        } else {
          couponInfoListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
       */
      public Builder addCouponInfoList(
          int index, com.akkw.protobuf.test.ptoto.CouponProto.Coupon.Builder builderForValue) {
        if (couponInfoListBuilder_ == null) {
          ensureCouponInfoListIsMutable();
          couponInfoList_.add(index, builderForValue.build());
          onChanged();
        } else {
          couponInfoListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
       */
      public Builder addAllCouponInfoList(
          java.lang.Iterable<? extends com.akkw.protobuf.test.ptoto.CouponProto.Coupon> values) {
        if (couponInfoListBuilder_ == null) {
          ensureCouponInfoListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, couponInfoList_);
          onChanged();
        } else {
          couponInfoListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
       */
      public Builder clearCouponInfoList() {
        if (couponInfoListBuilder_ == null) {
          couponInfoList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          couponInfoListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
       */
      public Builder removeCouponInfoList(int index) {
        if (couponInfoListBuilder_ == null) {
          ensureCouponInfoListIsMutable();
          couponInfoList_.remove(index);
          onChanged();
        } else {
          couponInfoListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
       */
      public com.akkw.protobuf.test.ptoto.CouponProto.Coupon.Builder getCouponInfoListBuilder(
          int index) {
        return getCouponInfoListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
       */
      public com.akkw.protobuf.test.ptoto.CouponProto.CouponOrBuilder getCouponInfoListOrBuilder(
          int index) {
        if (couponInfoListBuilder_ == null) {
          return couponInfoList_.get(index);  } else {
          return couponInfoListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
       */
      public java.util.List<? extends com.akkw.protobuf.test.ptoto.CouponProto.CouponOrBuilder> 
           getCouponInfoListOrBuilderList() {
        if (couponInfoListBuilder_ != null) {
          return couponInfoListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(couponInfoList_);
        }
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
       */
      public com.akkw.protobuf.test.ptoto.CouponProto.Coupon.Builder addCouponInfoListBuilder() {
        return getCouponInfoListFieldBuilder().addBuilder(
            com.akkw.protobuf.test.ptoto.CouponProto.Coupon.getDefaultInstance());
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
       */
      public com.akkw.protobuf.test.ptoto.CouponProto.Coupon.Builder addCouponInfoListBuilder(
          int index) {
        return getCouponInfoListFieldBuilder().addBuilder(
            index, com.akkw.protobuf.test.ptoto.CouponProto.Coupon.getDefaultInstance());
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.Coupon couponInfoList = 1;</code>
       */
      public java.util.List<com.akkw.protobuf.test.ptoto.CouponProto.Coupon.Builder> 
           getCouponInfoListBuilderList() {
        return getCouponInfoListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.akkw.protobuf.test.ptoto.CouponProto.Coupon, com.akkw.protobuf.test.ptoto.CouponProto.Coupon.Builder, com.akkw.protobuf.test.ptoto.CouponProto.CouponOrBuilder> 
          getCouponInfoListFieldBuilder() {
        if (couponInfoListBuilder_ == null) {
          couponInfoListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.akkw.protobuf.test.ptoto.CouponProto.Coupon, com.akkw.protobuf.test.ptoto.CouponProto.Coupon.Builder, com.akkw.protobuf.test.ptoto.CouponProto.CouponOrBuilder>(
                  couponInfoList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          couponInfoList_ = null;
        }
        return couponInfoListBuilder_;
      }

      private java.util.List<com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail> couponDetailInfoList_ =
        java.util.Collections.emptyList();
      private void ensureCouponDetailInfoListIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          couponDetailInfoList_ = new java.util.ArrayList<com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail>(couponDetailInfoList_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail.Builder, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetailOrBuilder> couponDetailInfoListBuilder_;

      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
       */
      public java.util.List<com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail> getCouponDetailInfoListList() {
        if (couponDetailInfoListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(couponDetailInfoList_);
        } else {
          return couponDetailInfoListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
       */
      public int getCouponDetailInfoListCount() {
        if (couponDetailInfoListBuilder_ == null) {
          return couponDetailInfoList_.size();
        } else {
          return couponDetailInfoListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
       */
      public com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail getCouponDetailInfoList(int index) {
        if (couponDetailInfoListBuilder_ == null) {
          return couponDetailInfoList_.get(index);
        } else {
          return couponDetailInfoListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
       */
      public Builder setCouponDetailInfoList(
          int index, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail value) {
        if (couponDetailInfoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCouponDetailInfoListIsMutable();
          couponDetailInfoList_.set(index, value);
          onChanged();
        } else {
          couponDetailInfoListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
       */
      public Builder setCouponDetailInfoList(
          int index, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail.Builder builderForValue) {
        if (couponDetailInfoListBuilder_ == null) {
          ensureCouponDetailInfoListIsMutable();
          couponDetailInfoList_.set(index, builderForValue.build());
          onChanged();
        } else {
          couponDetailInfoListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
       */
      public Builder addCouponDetailInfoList(com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail value) {
        if (couponDetailInfoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCouponDetailInfoListIsMutable();
          couponDetailInfoList_.add(value);
          onChanged();
        } else {
          couponDetailInfoListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
       */
      public Builder addCouponDetailInfoList(
          int index, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail value) {
        if (couponDetailInfoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCouponDetailInfoListIsMutable();
          couponDetailInfoList_.add(index, value);
          onChanged();
        } else {
          couponDetailInfoListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
       */
      public Builder addCouponDetailInfoList(
          com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail.Builder builderForValue) {
        if (couponDetailInfoListBuilder_ == null) {
          ensureCouponDetailInfoListIsMutable();
          couponDetailInfoList_.add(builderForValue.build());
          onChanged();
        } else {
          couponDetailInfoListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
       */
      public Builder addCouponDetailInfoList(
          int index, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail.Builder builderForValue) {
        if (couponDetailInfoListBuilder_ == null) {
          ensureCouponDetailInfoListIsMutable();
          couponDetailInfoList_.add(index, builderForValue.build());
          onChanged();
        } else {
          couponDetailInfoListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
       */
      public Builder addAllCouponDetailInfoList(
          java.lang.Iterable<? extends com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail> values) {
        if (couponDetailInfoListBuilder_ == null) {
          ensureCouponDetailInfoListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, couponDetailInfoList_);
          onChanged();
        } else {
          couponDetailInfoListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
       */
      public Builder clearCouponDetailInfoList() {
        if (couponDetailInfoListBuilder_ == null) {
          couponDetailInfoList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          couponDetailInfoListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
       */
      public Builder removeCouponDetailInfoList(int index) {
        if (couponDetailInfoListBuilder_ == null) {
          ensureCouponDetailInfoListIsMutable();
          couponDetailInfoList_.remove(index);
          onChanged();
        } else {
          couponDetailInfoListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
       */
      public com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail.Builder getCouponDetailInfoListBuilder(
          int index) {
        return getCouponDetailInfoListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
       */
      public com.akkw.protobuf.test.ptoto.CouponProto.CouponDetailOrBuilder getCouponDetailInfoListOrBuilder(
          int index) {
        if (couponDetailInfoListBuilder_ == null) {
          return couponDetailInfoList_.get(index);  } else {
          return couponDetailInfoListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
       */
      public java.util.List<? extends com.akkw.protobuf.test.ptoto.CouponProto.CouponDetailOrBuilder> 
           getCouponDetailInfoListOrBuilderList() {
        if (couponDetailInfoListBuilder_ != null) {
          return couponDetailInfoListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(couponDetailInfoList_);
        }
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
       */
      public com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail.Builder addCouponDetailInfoListBuilder() {
        return getCouponDetailInfoListFieldBuilder().addBuilder(
            com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
       */
      public com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail.Builder addCouponDetailInfoListBuilder(
          int index) {
        return getCouponDetailInfoListFieldBuilder().addBuilder(
            index, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .com.akkw.protobuf.test.ptoto.CouponDetail couponDetailInfoList = 2;</code>
       */
      public java.util.List<com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail.Builder> 
           getCouponDetailInfoListBuilderList() {
        return getCouponDetailInfoListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail.Builder, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetailOrBuilder> 
          getCouponDetailInfoListFieldBuilder() {
        if (couponDetailInfoListBuilder_ == null) {
          couponDetailInfoListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail.Builder, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetailOrBuilder>(
                  couponDetailInfoList_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          couponDetailInfoList_ = null;
        }
        return couponDetailInfoListBuilder_;
      }

      private java.lang.Object invokeSource_ = "";
      /**
       * <code>string invokeSource = 3;</code>
       * @return The invokeSource.
       */
      public java.lang.String getInvokeSource() {
        java.lang.Object ref = invokeSource_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          invokeSource_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string invokeSource = 3;</code>
       * @return The bytes for invokeSource.
       */
      public com.google.protobuf.ByteString
          getInvokeSourceBytes() {
        java.lang.Object ref = invokeSource_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          invokeSource_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string invokeSource = 3;</code>
       * @param value The invokeSource to set.
       * @return This builder for chaining.
       */
      public Builder setInvokeSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        invokeSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string invokeSource = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearInvokeSource() {
        
        invokeSource_ = getDefaultInstance().getInvokeSource();
        onChanged();
        return this;
      }
      /**
       * <code>string invokeSource = 3;</code>
       * @param value The bytes for invokeSource to set.
       * @return This builder for chaining.
       */
      public Builder setInvokeSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        invokeSource_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> extMap_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetExtMap() {
        if (extMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ExtMapDefaultEntryHolder.defaultEntry);
        }
        return extMap_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableExtMap() {
        onChanged();;
        if (extMap_ == null) {
          extMap_ = com.google.protobuf.MapField.newMapField(
              ExtMapDefaultEntryHolder.defaultEntry);
        }
        if (!extMap_.isMutable()) {
          extMap_ = extMap_.copy();
        }
        return extMap_;
      }

      public int getExtMapCount() {
        return internalGetExtMap().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; extMap = 4;</code>
       */

      @java.lang.Override
      public boolean containsExtMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetExtMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getExtMapMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getExtMap() {
        return getExtMapMap();
      }
      /**
       * <code>map&lt;string, string&gt; extMap = 4;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getExtMapMap() {
        return internalGetExtMap().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; extMap = 4;</code>
       */
      @java.lang.Override

      public java.lang.String getExtMapOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetExtMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; extMap = 4;</code>
       */
      @java.lang.Override

      public java.lang.String getExtMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetExtMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearExtMap() {
        internalGetMutableExtMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; extMap = 4;</code>
       */

      public Builder removeExtMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableExtMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableExtMap() {
        return internalGetMutableExtMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; extMap = 4;</code>
       */
      public Builder putExtMap(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableExtMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; extMap = 4;</code>
       */

      public Builder putAllExtMap(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableExtMap().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.akkw.protobuf.test.ptoto.CouponWriteParam)
    }

    // @@protoc_insertion_point(class_scope:com.akkw.protobuf.test.ptoto.CouponWriteParam)
    private static final com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam();
    }

    public static com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CouponWriteParam>
        PARSER = new com.google.protobuf.AbstractParser<CouponWriteParam>() {
      @java.lang.Override
      public CouponWriteParam parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CouponWriteParam> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CouponWriteParam> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.akkw.protobuf.test.ptoto.CouponWriteParamProto.CouponWriteParam getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_akkw_protobuf_test_ptoto_CouponWriteParam_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_akkw_protobuf_test_ptoto_CouponWriteParam_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_akkw_protobuf_test_ptoto_CouponWriteParam_ExtMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_akkw_protobuf_test_ptoto_CouponWriteParam_ExtMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026CouponWriteParam.proto\022\034com.akkw.proto" +
      "buf.test.ptoto\032\014coupon.proto\"\253\002\n\020CouponW" +
      "riteParam\022<\n\016couponInfoList\030\001 \003(\0132$.com." +
      "akkw.protobuf.test.ptoto.Coupon\022H\n\024coupo" +
      "nDetailInfoList\030\002 \003(\0132*.com.akkw.protobu" +
      "f.test.ptoto.CouponDetail\022\024\n\014invokeSourc" +
      "e\030\003 \001(\t\022J\n\006extMap\030\004 \003(\0132:.com.akkw.proto" +
      "buf.test.ptoto.CouponWriteParam.ExtMapEn" +
      "try\032-\n\013ExtMapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\t:\0028\001B5\n\034com.akkw.protobuf.test.pto" +
      "toB\025CouponWriteParamProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.akkw.protobuf.test.ptoto.CouponProto.getDescriptor(),
        });
    internal_static_com_akkw_protobuf_test_ptoto_CouponWriteParam_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_akkw_protobuf_test_ptoto_CouponWriteParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_akkw_protobuf_test_ptoto_CouponWriteParam_descriptor,
        new java.lang.String[] { "CouponInfoList", "CouponDetailInfoList", "InvokeSource", "ExtMap", });
    internal_static_com_akkw_protobuf_test_ptoto_CouponWriteParam_ExtMapEntry_descriptor =
      internal_static_com_akkw_protobuf_test_ptoto_CouponWriteParam_descriptor.getNestedTypes().get(0);
    internal_static_com_akkw_protobuf_test_ptoto_CouponWriteParam_ExtMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_akkw_protobuf_test_ptoto_CouponWriteParam_ExtMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.akkw.protobuf.test.ptoto.CouponProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
