// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MapParam.proto

package com.akkw.protobuf.test.ptoto;

public final class MapExampleProto {
  private MapExampleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MapExampleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.akkw.protobuf.test.ptoto.MapExample)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.Coupon&gt; couponMap = 1;</code>
     */
    int getCouponMapCount();
    /**
     * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.Coupon&gt; couponMap = 1;</code>
     */
    boolean containsCouponMap(
        java.lang.String key);
    /**
     * Use {@link #getCouponMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon>
    getCouponMap();
    /**
     * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.Coupon&gt; couponMap = 1;</code>
     */
    java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon>
    getCouponMapMap();
    /**
     * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.Coupon&gt; couponMap = 1;</code>
     */

    com.akkw.protobuf.test.ptoto.CouponProto.Coupon getCouponMapOrDefault(
        java.lang.String key,
        com.akkw.protobuf.test.ptoto.CouponProto.Coupon defaultValue);
    /**
     * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.Coupon&gt; couponMap = 1;</code>
     */

    com.akkw.protobuf.test.ptoto.CouponProto.Coupon getCouponMapOrThrow(
        java.lang.String key);

    /**
     * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.CouponDetail&gt; couponDetail = 2;</code>
     */
    int getCouponDetailCount();
    /**
     * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.CouponDetail&gt; couponDetail = 2;</code>
     */
    boolean containsCouponDetail(
        java.lang.String key);
    /**
     * Use {@link #getCouponDetailMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail>
    getCouponDetail();
    /**
     * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.CouponDetail&gt; couponDetail = 2;</code>
     */
    java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail>
    getCouponDetailMap();
    /**
     * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.CouponDetail&gt; couponDetail = 2;</code>
     */

    com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail getCouponDetailOrDefault(
        java.lang.String key,
        com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail defaultValue);
    /**
     * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.CouponDetail&gt; couponDetail = 2;</code>
     */

    com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail getCouponDetailOrThrow(
        java.lang.String key);

    /**
     * <code>map&lt;string, string&gt; stringMap = 3;</code>
     */
    int getStringMapCount();
    /**
     * <code>map&lt;string, string&gt; stringMap = 3;</code>
     */
    boolean containsStringMap(
        java.lang.String key);
    /**
     * Use {@link #getStringMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getStringMap();
    /**
     * <code>map&lt;string, string&gt; stringMap = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getStringMapMap();
    /**
     * <code>map&lt;string, string&gt; stringMap = 3;</code>
     */

    java.lang.String getStringMapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; stringMap = 3;</code>
     */

    java.lang.String getStringMapOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   *创建一个 User 对象
   * </pre>
   *
   * Protobuf type {@code com.akkw.protobuf.test.ptoto.MapExample}
   */
  public static final class MapExample extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.akkw.protobuf.test.ptoto.MapExample)
      MapExampleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MapExample.newBuilder() to construct.
    private MapExample(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MapExample() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MapExample();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akkw.protobuf.test.ptoto.MapExampleProto.internal_static_com_akkw_protobuf_test_ptoto_MapExample_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetCouponMap();
        case 2:
          return internalGetCouponDetail();
        case 3:
          return internalGetStringMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akkw.protobuf.test.ptoto.MapExampleProto.internal_static_com_akkw_protobuf_test_ptoto_MapExample_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample.class, com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample.Builder.class);
    }

    public static final int COUPONMAP_FIELD_NUMBER = 1;
    private static final class CouponMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon>newDefaultInstance(
                  com.akkw.protobuf.test.ptoto.MapExampleProto.internal_static_com_akkw_protobuf_test_ptoto_MapExample_CouponMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.akkw.protobuf.test.ptoto.CouponProto.Coupon.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon> couponMap_;
    private com.google.protobuf.MapField<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon>
    internalGetCouponMap() {
      if (couponMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CouponMapDefaultEntryHolder.defaultEntry);
      }
      return couponMap_;
    }

    public int getCouponMapCount() {
      return internalGetCouponMap().getMap().size();
    }
    /**
     * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.Coupon&gt; couponMap = 1;</code>
     */

    @java.lang.Override
    public boolean containsCouponMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetCouponMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCouponMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon> getCouponMap() {
      return getCouponMapMap();
    }
    /**
     * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.Coupon&gt; couponMap = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon> getCouponMapMap() {
      return internalGetCouponMap().getMap();
    }
    /**
     * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.Coupon&gt; couponMap = 1;</code>
     */
    @java.lang.Override

    public com.akkw.protobuf.test.ptoto.CouponProto.Coupon getCouponMapOrDefault(
        java.lang.String key,
        com.akkw.protobuf.test.ptoto.CouponProto.Coupon defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon> map =
          internalGetCouponMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.Coupon&gt; couponMap = 1;</code>
     */
    @java.lang.Override

    public com.akkw.protobuf.test.ptoto.CouponProto.Coupon getCouponMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon> map =
          internalGetCouponMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int COUPONDETAIL_FIELD_NUMBER = 2;
    private static final class CouponDetailDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail>newDefaultInstance(
                  com.akkw.protobuf.test.ptoto.MapExampleProto.internal_static_com_akkw_protobuf_test_ptoto_MapExample_CouponDetailEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail> couponDetail_;
    private com.google.protobuf.MapField<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail>
    internalGetCouponDetail() {
      if (couponDetail_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CouponDetailDefaultEntryHolder.defaultEntry);
      }
      return couponDetail_;
    }

    public int getCouponDetailCount() {
      return internalGetCouponDetail().getMap().size();
    }
    /**
     * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.CouponDetail&gt; couponDetail = 2;</code>
     */

    @java.lang.Override
    public boolean containsCouponDetail(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetCouponDetail().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCouponDetailMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail> getCouponDetail() {
      return getCouponDetailMap();
    }
    /**
     * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.CouponDetail&gt; couponDetail = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail> getCouponDetailMap() {
      return internalGetCouponDetail().getMap();
    }
    /**
     * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.CouponDetail&gt; couponDetail = 2;</code>
     */
    @java.lang.Override

    public com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail getCouponDetailOrDefault(
        java.lang.String key,
        com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail> map =
          internalGetCouponDetail().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.CouponDetail&gt; couponDetail = 2;</code>
     */
    @java.lang.Override

    public com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail getCouponDetailOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail> map =
          internalGetCouponDetail().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int STRINGMAP_FIELD_NUMBER = 3;
    private static final class StringMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.akkw.protobuf.test.ptoto.MapExampleProto.internal_static_com_akkw_protobuf_test_ptoto_MapExample_StringMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> stringMap_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetStringMap() {
      if (stringMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            StringMapDefaultEntryHolder.defaultEntry);
      }
      return stringMap_;
    }

    public int getStringMapCount() {
      return internalGetStringMap().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; stringMap = 3;</code>
     */

    @java.lang.Override
    public boolean containsStringMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetStringMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getStringMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getStringMap() {
      return getStringMapMap();
    }
    /**
     * <code>map&lt;string, string&gt; stringMap = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getStringMapMap() {
      return internalGetStringMap().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; stringMap = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getStringMapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetStringMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; stringMap = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getStringMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetStringMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetCouponMap(),
          CouponMapDefaultEntryHolder.defaultEntry,
          1);
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetCouponDetail(),
          CouponDetailDefaultEntryHolder.defaultEntry,
          2);
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetStringMap(),
          StringMapDefaultEntryHolder.defaultEntry,
          3);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon> entry
           : internalGetCouponMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon>
        couponMap__ = CouponMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, couponMap__);
      }
      for (java.util.Map.Entry<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail> entry
           : internalGetCouponDetail().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail>
        couponDetail__ = CouponDetailDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, couponDetail__);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetStringMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        stringMap__ = StringMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, stringMap__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample)) {
        return super.equals(obj);
      }
      com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample other = (com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample) obj;

      if (!internalGetCouponMap().equals(
          other.internalGetCouponMap())) return false;
      if (!internalGetCouponDetail().equals(
          other.internalGetCouponDetail())) return false;
      if (!internalGetStringMap().equals(
          other.internalGetStringMap())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetCouponMap().getMap().isEmpty()) {
        hash = (37 * hash) + COUPONMAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetCouponMap().hashCode();
      }
      if (!internalGetCouponDetail().getMap().isEmpty()) {
        hash = (37 * hash) + COUPONDETAIL_FIELD_NUMBER;
        hash = (53 * hash) + internalGetCouponDetail().hashCode();
      }
      if (!internalGetStringMap().getMap().isEmpty()) {
        hash = (37 * hash) + STRINGMAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetStringMap().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *创建一个 User 对象
     * </pre>
     *
     * Protobuf type {@code com.akkw.protobuf.test.ptoto.MapExample}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.akkw.protobuf.test.ptoto.MapExample)
        com.akkw.protobuf.test.ptoto.MapExampleProto.MapExampleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akkw.protobuf.test.ptoto.MapExampleProto.internal_static_com_akkw_protobuf_test_ptoto_MapExample_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetCouponMap();
          case 2:
            return internalGetCouponDetail();
          case 3:
            return internalGetStringMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableCouponMap();
          case 2:
            return internalGetMutableCouponDetail();
          case 3:
            return internalGetMutableStringMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akkw.protobuf.test.ptoto.MapExampleProto.internal_static_com_akkw_protobuf_test_ptoto_MapExample_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample.class, com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample.Builder.class);
      }

      // Construct using com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableCouponMap().clear();
        internalGetMutableCouponDetail().clear();
        internalGetMutableStringMap().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akkw.protobuf.test.ptoto.MapExampleProto.internal_static_com_akkw_protobuf_test_ptoto_MapExample_descriptor;
      }

      @java.lang.Override
      public com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample getDefaultInstanceForType() {
        return com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample.getDefaultInstance();
      }

      @java.lang.Override
      public com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample build() {
        com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample buildPartial() {
        com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample result = new com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample(this);
        int from_bitField0_ = bitField0_;
        result.couponMap_ = internalGetCouponMap();
        result.couponMap_.makeImmutable();
        result.couponDetail_ = internalGetCouponDetail();
        result.couponDetail_.makeImmutable();
        result.stringMap_ = internalGetStringMap();
        result.stringMap_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample) {
          return mergeFrom((com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample other) {
        if (other == com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample.getDefaultInstance()) return this;
        internalGetMutableCouponMap().mergeFrom(
            other.internalGetCouponMap());
        internalGetMutableCouponDetail().mergeFrom(
            other.internalGetCouponDetail());
        internalGetMutableStringMap().mergeFrom(
            other.internalGetStringMap());
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.MapEntry<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon>
                couponMap__ = input.readMessage(
                    CouponMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableCouponMap().getMutableMap().put(
                    couponMap__.getKey(), couponMap__.getValue());
                break;
              } // case 10
              case 18: {
                com.google.protobuf.MapEntry<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail>
                couponDetail__ = input.readMessage(
                    CouponDetailDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableCouponDetail().getMutableMap().put(
                    couponDetail__.getKey(), couponDetail__.getValue());
                break;
              } // case 18
              case 26: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                stringMap__ = input.readMessage(
                    StringMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableStringMap().getMutableMap().put(
                    stringMap__.getKey(), stringMap__.getValue());
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon> couponMap_;
      private com.google.protobuf.MapField<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon>
      internalGetCouponMap() {
        if (couponMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              CouponMapDefaultEntryHolder.defaultEntry);
        }
        return couponMap_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon>
      internalGetMutableCouponMap() {
        onChanged();;
        if (couponMap_ == null) {
          couponMap_ = com.google.protobuf.MapField.newMapField(
              CouponMapDefaultEntryHolder.defaultEntry);
        }
        if (!couponMap_.isMutable()) {
          couponMap_ = couponMap_.copy();
        }
        return couponMap_;
      }

      public int getCouponMapCount() {
        return internalGetCouponMap().getMap().size();
      }
      /**
       * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.Coupon&gt; couponMap = 1;</code>
       */

      @java.lang.Override
      public boolean containsCouponMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetCouponMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getCouponMapMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon> getCouponMap() {
        return getCouponMapMap();
      }
      /**
       * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.Coupon&gt; couponMap = 1;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon> getCouponMapMap() {
        return internalGetCouponMap().getMap();
      }
      /**
       * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.Coupon&gt; couponMap = 1;</code>
       */
      @java.lang.Override

      public com.akkw.protobuf.test.ptoto.CouponProto.Coupon getCouponMapOrDefault(
          java.lang.String key,
          com.akkw.protobuf.test.ptoto.CouponProto.Coupon defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon> map =
            internalGetCouponMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.Coupon&gt; couponMap = 1;</code>
       */
      @java.lang.Override

      public com.akkw.protobuf.test.ptoto.CouponProto.Coupon getCouponMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon> map =
            internalGetCouponMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearCouponMap() {
        internalGetMutableCouponMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.Coupon&gt; couponMap = 1;</code>
       */

      public Builder removeCouponMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableCouponMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon>
      getMutableCouponMap() {
        return internalGetMutableCouponMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.Coupon&gt; couponMap = 1;</code>
       */
      public Builder putCouponMap(
          java.lang.String key,
          com.akkw.protobuf.test.ptoto.CouponProto.Coupon value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableCouponMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.Coupon&gt; couponMap = 1;</code>
       */

      public Builder putAllCouponMap(
          java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.Coupon> values) {
        internalGetMutableCouponMap().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail> couponDetail_;
      private com.google.protobuf.MapField<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail>
      internalGetCouponDetail() {
        if (couponDetail_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              CouponDetailDefaultEntryHolder.defaultEntry);
        }
        return couponDetail_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail>
      internalGetMutableCouponDetail() {
        onChanged();;
        if (couponDetail_ == null) {
          couponDetail_ = com.google.protobuf.MapField.newMapField(
              CouponDetailDefaultEntryHolder.defaultEntry);
        }
        if (!couponDetail_.isMutable()) {
          couponDetail_ = couponDetail_.copy();
        }
        return couponDetail_;
      }

      public int getCouponDetailCount() {
        return internalGetCouponDetail().getMap().size();
      }
      /**
       * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.CouponDetail&gt; couponDetail = 2;</code>
       */

      @java.lang.Override
      public boolean containsCouponDetail(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetCouponDetail().getMap().containsKey(key);
      }
      /**
       * Use {@link #getCouponDetailMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail> getCouponDetail() {
        return getCouponDetailMap();
      }
      /**
       * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.CouponDetail&gt; couponDetail = 2;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail> getCouponDetailMap() {
        return internalGetCouponDetail().getMap();
      }
      /**
       * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.CouponDetail&gt; couponDetail = 2;</code>
       */
      @java.lang.Override

      public com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail getCouponDetailOrDefault(
          java.lang.String key,
          com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail> map =
            internalGetCouponDetail().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.CouponDetail&gt; couponDetail = 2;</code>
       */
      @java.lang.Override

      public com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail getCouponDetailOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail> map =
            internalGetCouponDetail().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearCouponDetail() {
        internalGetMutableCouponDetail().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.CouponDetail&gt; couponDetail = 2;</code>
       */

      public Builder removeCouponDetail(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableCouponDetail().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail>
      getMutableCouponDetail() {
        return internalGetMutableCouponDetail().getMutableMap();
      }
      /**
       * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.CouponDetail&gt; couponDetail = 2;</code>
       */
      public Builder putCouponDetail(
          java.lang.String key,
          com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableCouponDetail().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .com.akkw.protobuf.test.ptoto.CouponDetail&gt; couponDetail = 2;</code>
       */

      public Builder putAllCouponDetail(
          java.util.Map<java.lang.String, com.akkw.protobuf.test.ptoto.CouponProto.CouponDetail> values) {
        internalGetMutableCouponDetail().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> stringMap_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetStringMap() {
        if (stringMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              StringMapDefaultEntryHolder.defaultEntry);
        }
        return stringMap_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableStringMap() {
        onChanged();;
        if (stringMap_ == null) {
          stringMap_ = com.google.protobuf.MapField.newMapField(
              StringMapDefaultEntryHolder.defaultEntry);
        }
        if (!stringMap_.isMutable()) {
          stringMap_ = stringMap_.copy();
        }
        return stringMap_;
      }

      public int getStringMapCount() {
        return internalGetStringMap().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; stringMap = 3;</code>
       */

      @java.lang.Override
      public boolean containsStringMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetStringMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getStringMapMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getStringMap() {
        return getStringMapMap();
      }
      /**
       * <code>map&lt;string, string&gt; stringMap = 3;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getStringMapMap() {
        return internalGetStringMap().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; stringMap = 3;</code>
       */
      @java.lang.Override

      public java.lang.String getStringMapOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetStringMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; stringMap = 3;</code>
       */
      @java.lang.Override

      public java.lang.String getStringMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetStringMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearStringMap() {
        internalGetMutableStringMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; stringMap = 3;</code>
       */

      public Builder removeStringMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableStringMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableStringMap() {
        return internalGetMutableStringMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; stringMap = 3;</code>
       */
      public Builder putStringMap(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableStringMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; stringMap = 3;</code>
       */

      public Builder putAllStringMap(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableStringMap().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.akkw.protobuf.test.ptoto.MapExample)
    }

    // @@protoc_insertion_point(class_scope:com.akkw.protobuf.test.ptoto.MapExample)
    private static final com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample();
    }

    public static com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MapExample>
        PARSER = new com.google.protobuf.AbstractParser<MapExample>() {
      @java.lang.Override
      public MapExample parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MapExample> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MapExample> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.akkw.protobuf.test.ptoto.MapExampleProto.MapExample getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_akkw_protobuf_test_ptoto_MapExample_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_akkw_protobuf_test_ptoto_MapExample_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_akkw_protobuf_test_ptoto_MapExample_CouponMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_akkw_protobuf_test_ptoto_MapExample_CouponMapEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_akkw_protobuf_test_ptoto_MapExample_CouponDetailEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_akkw_protobuf_test_ptoto_MapExample_CouponDetailEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_akkw_protobuf_test_ptoto_MapExample_StringMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_akkw_protobuf_test_ptoto_MapExample_StringMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016MapParam.proto\022\034com.akkw.protobuf.test" +
      ".ptoto\032\014coupon.proto\"\341\003\n\nMapExample\022J\n\tc" +
      "ouponMap\030\001 \003(\01327.com.akkw.protobuf.test." +
      "ptoto.MapExample.CouponMapEntry\022P\n\014coupo" +
      "nDetail\030\002 \003(\0132:.com.akkw.protobuf.test.p" +
      "toto.MapExample.CouponDetailEntry\022J\n\tstr" +
      "ingMap\030\003 \003(\01327.com.akkw.protobuf.test.pt" +
      "oto.MapExample.StringMapEntry\032V\n\016CouponM" +
      "apEntry\022\013\n\003key\030\001 \001(\t\0223\n\005value\030\002 \001(\0132$.co" +
      "m.akkw.protobuf.test.ptoto.Coupon:\0028\001\032_\n" +
      "\021CouponDetailEntry\022\013\n\003key\030\001 \001(\t\0229\n\005value" +
      "\030\002 \001(\0132*.com.akkw.protobuf.test.ptoto.Co" +
      "uponDetail:\0028\001\0320\n\016StringMapEntry\022\013\n\003key\030" +
      "\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B/\n\034com.akkw.pro" +
      "tobuf.test.ptotoB\017MapExampleProtob\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.akkw.protobuf.test.ptoto.CouponProto.getDescriptor(),
        });
    internal_static_com_akkw_protobuf_test_ptoto_MapExample_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_akkw_protobuf_test_ptoto_MapExample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_akkw_protobuf_test_ptoto_MapExample_descriptor,
        new java.lang.String[] { "CouponMap", "CouponDetail", "StringMap", });
    internal_static_com_akkw_protobuf_test_ptoto_MapExample_CouponMapEntry_descriptor =
      internal_static_com_akkw_protobuf_test_ptoto_MapExample_descriptor.getNestedTypes().get(0);
    internal_static_com_akkw_protobuf_test_ptoto_MapExample_CouponMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_akkw_protobuf_test_ptoto_MapExample_CouponMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_akkw_protobuf_test_ptoto_MapExample_CouponDetailEntry_descriptor =
      internal_static_com_akkw_protobuf_test_ptoto_MapExample_descriptor.getNestedTypes().get(1);
    internal_static_com_akkw_protobuf_test_ptoto_MapExample_CouponDetailEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_akkw_protobuf_test_ptoto_MapExample_CouponDetailEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_akkw_protobuf_test_ptoto_MapExample_StringMapEntry_descriptor =
      internal_static_com_akkw_protobuf_test_ptoto_MapExample_descriptor.getNestedTypes().get(2);
    internal_static_com_akkw_protobuf_test_ptoto_MapExample_StringMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_akkw_protobuf_test_ptoto_MapExample_StringMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.akkw.protobuf.test.ptoto.CouponProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
